/* Pre-compiles all the JSX source files into a single bundle.js so the
 * browser doesn't have to download Babel (~2.8MB) and compile 22 files on
 * every page load. Run `node build.js` after editing any .jsx source.
 *
 * Each file is wrapped in its own function scope with React/ReactDOM in
 * scope — identical semantics to the old in-browser loader, just done once
 * ahead of time. The .jsx files remain the source of truth. */
const fs = require('fs');
const path = require('path');
const Babel = require('@babel/standalone');

// Same order the in-browser loader used: sections register into window.__S,
// App.jsx renders #root, mobile files register into window.__M, MApp renders #mroot.
const FILES = [
  'sections/01-hero.jsx',
  'sections/02-awards.jsx',
  'sections/03-categories.jsx',
  'sections/04-templates.jsx',
  'sections/05-testimonials.jsx',
  'sections/06-feature.jsx',
  'sections/07-pricing.jsx',
  'sections/08-watch-the-fold.jsx',
  'sections/09-cta.jsx',
  'sections/10-footer.jsx',
  'App.jsx',
  'mobile/m01-hero.jsx',
  'mobile/m02-awards.jsx',
  'mobile/m03-categories.jsx',
  'mobile/m04-templates.jsx',
  'mobile/m05-feature.jsx',
  'mobile/m06-watch.jsx',
  'mobile/m07-testimonials.jsx',
  'mobile/m08-pricing.jsx',
  'mobile/m09-cta.jsx',
  'mobile/m10-footer.jsx',
  'mobile/MApp.jsx',
];

let out = '/* AUTO-GENERATED by build.js — do not edit by hand. Edit the .jsx sources and re-run `node build.js`. */\n';
for (const f of FILES) {
  const src = fs.readFileSync(path.join(__dirname, f), 'utf8');
  const code = Babel.transform(src, { presets: [['react', { runtime: 'classic' }]], filename: f }).code;
  out += `\n/* ===== ${f} ===== */\n(function (React, ReactDOM) {\n${code}\n})(window.React, window.ReactDOM);\n`;
}
fs.writeFileSync(path.join(__dirname, 'bundle.js'), out);
console.log('wrote bundle.js —', (out.length / 1024).toFixed(0) + 'KB,', FILES.length, 'files');
